### PR TITLE
Fix for "Attempted to dequeue multiple cells for the same index path" in table views with Xcode 9

### LINKED ISSUE #1007: NSInternalInconsistencyException scrolling UITableViews
Hi there - we're getting this error using the latest version of KIF on any `waitForView(withAccessibilityLabel:)` or `tapView(withAccessibilityLabel:)` that tries to interact with a UITableView:

```
Attempted to dequeue multiple cells for the same index path, which is not allowed. If you really need to dequeue more cells than the table view is requesting, use the -dequeueReusableCellWithIdentifier: method (without an index path). Cell identifier: cell, index path: <NSIndexPath: 0x600000a360a0> {length = 2, path = 0 - 7}
```
The offending code seems to be in `UIView+KIFAdditions.m`, line 254:

`UITableViewCell *cell = [tableView.dataSource tableView:tableView cellForRowAtIndexPath:indexPath];`

It's looking like to us that the issue is related to how that function looping through all the cells in a tableview to find its position, which either fails or takes a considerable amount of time, causing the operation to retry, or the tests to hang/fail. Commenting out this code (lines 252 - 273) allows the tests to progress naturally without interruption. Also, adding a significant amount of time padding (5-10s) for the view to load in with `tester().wait(forTimeInterval:)` before calling `waitForView` or `tapView` seems to help, though this adds significant time to testing.

Even though the code is reused for collectionviews, it doesn't seem like 

Seems like this is only an issue with Xcode 9 and 8.3.3 is unaffected. Stack trace:

```
caught "NSInternalInconsistencyException", "Attempted to dequeue multiple cells for the same index path, which is not allowed. If you really need to dequeue more cells than the table view is requesting, use the -dequeueReusableCellWithIdentifier: method (without an index path). Cell identifier: cell, index path: <NSIndexPath: 0x60c000a3e0e0> {length = 2, path = 0 - 7}"
(
	0   CoreFoundation                      0x000000011374f1cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001184adf41 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000113754362 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000117f52089 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   UIKit                               0x0000000115b737b4 -[UITableView _dequeueReusableCellWithIdentifier:forIndexPath:usingPresentationValues:] + 454
	5   UIKit                               0x0000000115b735ba -[UITableView dequeueReusableCellWithIdentifier:forIndexPath:] + 89
	6   UIKit                               0x000000013cfdc4b3 -[UITableViewAccessibility dequeueReusableCellWithIdentifier:forIndexPath:] + 285
	7   DoordashConsumer                    0x000000011044b7c3 _T016DoordashConsumer19OrderListDatasourceC9tableViewSo07UITableG4CellCSo0hG0C_10Foundation9IndexPathV12cellForRowAttF + 1907
	8   DoordashConsumer                    0x000000011044ba6c _T016DoordashConsumer19OrderListDatasourceC9tableViewSo07UITableG4CellCSo0hG0C_10Foundation9IndexPathV12cellForRowAttFTo + 92
	9   KIF                                 0x0000000139d2f81e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 3822
	10  KIF                                 0x0000000139d2e8f8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	11  KIF                                 0x0000000139d2ec8e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 862
	12  KIF                                 0x0000000139d2e8f8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	13  KIF                                 0x0000000139d2ec8e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 862
	14  KIF                                 0x0000000139d2e8f8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	15  KIF                                 0x0000000139d2ec8e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 862
	16  KIF                                 0x0000000139d2e8f8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	17  KIF                                 0x0000000139d2ec8e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 862
	18  KIF                                 0x0000000139d2e8f8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	19  KIF                                 0x0000000139d2ec8e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 862
	20  KIF                                 0x0000000139d2e8f8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	21  KIF                                 0x0000000139d2ec8e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 862
	22  KIF                                 0x0000000139d2e8f8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	23  KIF                                 0x0000000139d2ec8e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 862
	24  KIF                                 0x0000000139d2e8f8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	25  KIF                                 0x0000000139d2ec8e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 862
	26  KIF                                 0x0000000139d2e8f8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	27  KIF                                 0x0000000139d2e079 -[UIView(KIFAdditions) accessibilityElementWithLabel:accessibilityValue:traits:] + 249
	28  KIF                                 0x0000000139d2731e -[UIApplication(KIFAdditions) accessibilityElementWithLabel:accessibilityValue:traits:] + 542
	29  KIF                                 0x0000000139d24cb1 +[UIAccessibilityElement(KIFAdditions) accessibilityElementWithLabel:value:traits:fromRootView:error:] + 417
	30  KIF                                 0x0000000139d24222 +[UIAccessibilityElement(KIFAdditions) accessibilityElement:view:withLabel:value:traits:fromRootView:tappable:error:] + 258
	31  KIF                                 0x0000000139d240db +[UIAccessibilityElement(KIFAdditions) accessibilityElement:view:withLabel:value:traits:tappable:error:] + 235
	32  KIF                                 0x0000000139d0e5b2 __83-[KIFUITestActor waitForAccessibilityElement:view:withLabel:value:traits:tappable:]_block_invoke + 114
	33  KIF                                 0x0000000139d0a5b7 -[KIFTestActor tryRunningBlock:complete:timeout:error:] + 167
	34  KIF                                 0x0000000139d0a8a9 -[KIFTestActor runBlock:complete:timeout:] + 137
	35  KIF                                 0x0000000139d0a9b4 -[KIFTestActor runBlock:complete:] + 148
	36  KIF                                 0x0000000139d0aa90 -[KIFTestActor runBlock:] + 64
	37  KIF                                 0x0000000139d0e4db -[KIFUITestActor waitForAccessibilityElement:view:withLabel:value:traits:tappable:] + 331
	38  KIF                                 0x0000000139d0e30e -[KIFUITestActor waitForViewWithAccessibilityLabel:value:traits:tappable:] + 206
	39  KIF                                 0x0000000139d0df60 -[KIFUITestActor waitForViewWithAccessibilityLabel:traits:] + 96
	40  DoordashConsumerFunctionalTests     0x0000000139caaa36 _T031DoordashConsumerFunctionalTests14A2CheckoutSpecC4specyyFyycfU_yycfU6_yycfU0_ + 214
	41  Quick                               0x0000000139f59c96 _T05Quick7ExampleC3runyyF + 2198
	42  Quick                               0x0000000139f5a8c4 _T05Quick7ExampleC3runyyFTo + 36
	43  Quick                               0x0000000139f5139b __60+[QuickSpec addInstanceMethodForExample:classSelectorNames:]_block_invoke + 123
	44  CoreFoundation                      0x00000001136d356c __invoking___ + 140
	45  CoreFoundation                      0x00000001136d3440 -[NSInvocation invoke] + 320
	46  XCTest                              0x00000001387a1949 __24-[XCTestCase invokeTest]_block_invoke + 591
	47  XCTest                              0x00000001387e9f45 -[XCUITestContext performInScope:] + 183
	48  XCTest                              0x00000001387a16ef -[XCTestCase invokeTest] + 141
	49  XCTest                              0x00000001387a26b0 __26-[XCTestCase performTest:]_block_invoke.369 + 42
	50  XCTest                              0x00000001387eec4b +[XCTContext runInContextForTestCase:block:] + 163
	51  XCTest                              0x00000001387a204c -[XCTestCase performTest:] + 608
	52  XCTest                              0x000000013879e052 __27-[XCTestSuite performTest:]_block_invoke + 363
	53  XCTest                              0x000000013879d9b9 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 26
	54  XCTest                              0x000000013879dbb6 -[XCTestSuite performTest:] + 239
	55  XCTest                              0x000000013879e052 __27-[XCTestSuite performTest:]_block_invoke + 363
	56  XCTest                              0x000000013879d9b9 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 26
	57  XCTest                              0x000000013879dbb6 -[XCTestSuite performTest:] + 239
	58  XCTest                              0x000000013879e052 __27-[XCTestSuite performTest:]_block_invoke + 363
	59  XCTest                              0x000000013879d9b9 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 26
	60  XCTest                              0x000000013879dbb6 -[XCTestSuite performTest:] + 239
	61  XCTest                              0x00000001387f616d __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 40
	62  XCTest                              0x00000001387b1232 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 475
	63  XCTest                              0x00000001387f600c -[XCTTestRunSession runTestsAndReturnError:] + 281
	64  XCTest                              0x000000013878d6ab -[XCTestDriver runTestsAndReturnError:] + 314
	65  XCTest                              0x00000001387edeb6 _XCTestMain + 619
	66  CoreFoundation                      0x00000001136f220c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	67  CoreFoundation                      0x00000001136d6a3b __CFRunLoopDoBlocks + 203
	68  CoreFoundation                      0x00000001136d6214 __CFRunLoopRun + 1300
	69  CoreFoundation                      0x00000001136d5a89 CFRunLoopRunSpecific + 409
	70  GraphicsServices                    0x000000011d5f79c6 GSEventRunModal + 62
	71  UIKit                               0x0000000115a35d30 UIApplicationMain + 159
	72  DoordashConsumer                    0x000000010f615227 main + 55
	73  libdyld.dylib                       0x0000000119ffcd81 start + 1
	74  ???                                 0x0000000000000005 0x0 + 5
```

### PR DESCRIPTION
**Pull request by mikelupo**
Fixes #1007

Trying out a fix for issue #1007.
@justinseanmartin @RoyalPineapple please have a look?

Thanks to Larry Gensch (non-github user at this time) who did all of the heavy lifting.

Thanks,
Mike

### CODE REVIEW

File: Additions/UIView-KIFAdditions.m [hunk 1]
```diff
@@ -247,32 +253,28 @@ - (UIAccessibilityElement *)accessibilityElementMatchingBlock:(BOOL(^)(UIAccessi
...
-                    // Scroll to the cell and wait for the animation to complete
-                    [tableView scrollToRowAtIndexPath:indexPath atScrollPosition:UITableViewScrollPositionNone animated:YES];
-                    // Note: using KIFRunLoopRunInModeRelativeToAnimationSpeed here may cause tests to stall
-                    CFRunLoopRunInMode(UIApplicationCurrentRunMode, 0.5, false);
-                    
+					}
+
+					@autoreleasepool {
+						// Scroll to the cell and wait for the animation to complete
+						[tableView scrollToRowAtIndexPath:indexPath atScrollPosition:UITableViewScrollPositionNone animated:NO];
```
Comment (justinseanmartin) [inline Additions/UIView-KIFAdditions.m]: The intent of the existing logic is to not scroll the tableview unless it is known that an element within that tableview should be made visible. 

Otherwise, we're taking a potentially huge performance penalty to scroll through all elements in table views to try and find an element that happens to be in the view hierarchy after the table view. This will still happen even if the table view is completely offscreen, right?

Have you noticed this when running your full suite of tests? Maybe it isn't so bad due to not animating the tableview scrolling.

Comment (mikelupo) [reply Additions/UIView-KIFAdditions.m]: Performance hit is minimal.

File: Additions/UIView-KIFAdditions.m [hunk 2]
```diff
@@ -247,32 +253,28 @@ - (UIAccessibilityElement *)accessibilityElementMatchingBlock:(BOOL(^)(UIAccessi
...
+						// Note: using KIFRunLoopRunInModeRelativeToAnimationSpeed here may cause tests to stall
```
[the remark this answers is not in the document]
Comment (mikelupo) [reply Additions/UIView-KIFAdditions.m]: That comment was in original code.

File: Additions/UIView-KIFAdditions.m [hunk 3]
```diff
@@ -247,32 +253,28 @@ - (UIAccessibilityElement *)accessibilityElementMatchingBlock:(BOOL(^)(UIAccessi
...
+
+						UITableViewCell *cell = [tableView cellForRowAtIndexPath:indexPath];
+						UIAccessibilityElement *element = [cell accessibilityElementMatchingBlock:matchBlock notHidden:NO];
+
+						// Skip this cell if it isn't the one we're looking for
+						if (!element) {
+							continue;
+						}
+					}
+					CFRunLoopRunInMode(UIApplicationCurrentRunMode, 0, false);
```
[the remark this answers is not in the document]
Comment (mikelupo) [reply Additions/UIView-KIFAdditions.m]: Optimization. Still it ensures that it runs on the correct thread.

File: Additions/UIView-KIFAdditions.m [hunk 4]
```diff
@@ -236,7 +236,13 @@ - (UIAccessibilityElement *)accessibilityElementMatchingBlock:(BOOL(^)(UIAccessi
                     [indexPathsForVisibleRows addObject:indexPath];
                 }
             }];
-            
+
+			NSIndexPath *firstIndexPath = indexPathsForVisibleRows.firstObject;
```
[the remark this answers is not in the document]
Comment (mikelupo) [reply Additions/UIView-KIFAdditions.m]: Yeah, I encounter this in just about every github repro. ;) You'd think I'd know by now.

**Comment by justinseanmartin** [comment]
Regarding Travis, I think there might be other issues we need to deal with to get those to go green with XC9. 

Last time I tried on XC8 (which we should also have CI coverage of but don't currently), the issues were with autocorrect kicking in and breaking some tests. We could fix them one-off by disabling auto-correct on those fields in the integration test app.

It looks like in your job, the XC9 job is failing a bunch of tests that likely need to be investigated to get that CI configuration added. I'll create an issue for that and track it in the XC9 project. You can remove that from this project for now. 

Ideally, you'd be able to create a test that when run locally against XC9, it shows it failing without the fix and passing with it. That test should also pass in XC6/7/8, so that would be fine. We just can't ensure we don't regress the behavior that is currently broken in XC9 without CI validating it. Having a test is better than nothing though if you understand it well enough.

File: Additions/UIView-KIFAdditions.m [hunk 5]
```diff
@@ -248,31 +256,29 @@ - (UIAccessibilityElement *)accessibilityElementMatchingBlock:(BOOL(^)(UIAccessi
...
-                        UITableViewCell *cell = [tableView.dataSource tableView:tableView cellForRowAtIndexPath:indexPath];
-                        
+                        // Scroll to the cell
+                        [tableView scrollToRowAtIndexPath:indexPath atScrollPosition:UITableViewScrollPositionNone animated:NO];
+
+                        UITableViewCell *cell = [tableView cellForRowAtIndexPath:indexPath];
                         UIAccessibilityElement *element = [cell accessibilityElementMatchingBlock:matchBlock notHidden:NO];
-                        
-                        // Remove the cell from the table view so that it doesn't stick around
-                        [cell removeFromSuperview];
```
Comment (justinseanmartin) [inline Additions/UIView-KIFAdditions.m]: This isn't necessary or caused some problem?

**Comment by justinseanmartin** [comment]
I'm still a bit concerned about calling `scroll` on the table view over and over as a solution of finding elements that are offscreen. My two concerns are:

1. Performance impact of general KIF usage that isn't impacted by this bug. Performing a single pass to find if an element is in the view hierarchy needs to be very fast.
2. It exercises the app in ways that a user never would, and could potentially lead to false negatives.

I'll pick up the patch and run our test suite with the change and see what happens. In the meantime, remove the XC9 travis config for now (unless you want to try and get it green before introducing this change), and try and get the existing configurations to go green in Travis.

Having a reproduction case in the integration tests that I can run locally and poke around in would be a huge help for understanding exactly what the issue is that we're trying to tackle.

**Comment by mikelupo** [comment]
@justinseanmartin I am working towards a green Travis run in between many other things. One major unresolved sticking point is the photo picker. I know your take is that we should not interact with it and obtain the photo by other programmatic means but I’m not convinced that we should as this makes KIF stand out. 
Oh, lastly, I think the Alert tests are failing too. I’ve not investigated. I may just skip those in iOS 11 but would rather not.

**Comment by mikelupo** [comment]
FYI, I've been running with this in my own automation without any failures for over a month now. It seems to perform OK too. I will get the XC9 config out. Let's try to get this merged soon so our community can continue using KIF on iOS 11.

**Comment by justinseanmartin** [comment]
That's great! I still have an IOU on running this against our tests. Removing XC9 CI config makes sense as far as this change is concerned.

I'm still wary of the overall approach of scrolling the view to find a matching element, but I'll take a look at it when running our test suite. I'll try to get to that soon.

File: Additions/UIView-KIFAdditions.m (hunk 5 above)
Comment (mikelupo) [reply Additions/UIView-KIFAdditions.m]: It seemed to my iOS developer colleague that it wasn't necessary.

**Comment by mikelupo** [comment]
@justinseanmartin updates made. With your approval, this could get merged as-is.

Thanks,
Mike

**Comment by mikelupo** [comment]
@justinseanmartin it looks like our code change broke the picker tests. Looking into it.

**Comment by edwinlai** [comment]
Is there any progress on this? I manually pointed KIF to this and it fixes the issue.

**Comment by mikelupo** [comment]
I’m not sure it’s ready for the masses but feel free to take the patch and use it. I am going to have to lean on @justinseanmartin for some help/advice here. I’ve not been able to give this patch any love for a while.

**Comment by justinseanmartin** [comment]
Yea, this is my bad, I've been swamped at work and haven't had time to test it out to see how it works. I'll try to get to it early next week or see if I can get someone else to help out testing our codebase with this change.

It is good to hear that this works for @edwinlai as well. I still wish that there was a test that could be used to replicate the failure and verify the fix doesn't regress.

**Comment by soleares** [comment]
@mikelupo @justinseanmartin This resolved the issue for us. I was able to remove all of the workarounds (1 sec async waits). Sanity restored! Thanks for working on this!

**Comment by charlyliu** [comment]
This also solve the tests for us.

**Comment by sirnacnud** [comment]
I also am running in to this assert with my tests and the PR from @mikelupo fixed it.

**Comment by justinseanmartin** [comment]
Sorry for the delay on getting this merged, been swamped. I'm glad this is working for people, and thanks again @mikelupo for helping address this. I'll see about merging this soon.

It is still unfortunate that we don't have a simple reproduction of the issue. Does someone have a small sample project that shows the issue happening?

**Comment by lyptt** [comment]
@justinseanmartin for me at least, simple projects never reproduced the issue. Complex UI layouts that were part of real applications were the only trigger.

**Comment by kenji21** [comment]
Got the issue with an empty tableview (but having a tableHeaderView added within the xib file)

**Comment by justinseanmartin** [comment]
@kenji21 - Do you have a sample project that I could look at for the repro?

**Comment by kenji21** [comment]
Very hard to find, but the issue comes this line in my client project:
````
self.headerLabelHeightConstraint.constant = self.tableView.bounds.size.height;
````

If I comment it, or change it to:
````
self.headerLabelHeightConstraint.constant = self.tableView.bounds.size.height / 2.0;
````

then the `Attempted to dequeue multiple cells` disappears...

I tried to reproduce the issue in an empty project, with as few code as possible, but the issue doesn't appears... On my client project, cellForRowAtIndexPath is only called two times (second time making it crash).

So instead of trying to reproduce the issue, I've cloned and checkout the branch fixForIssue1007 of mikelupo/KIF, and I can confirm it fix the crash.

**Comment by justinseanmartin** [comment]
This is very helpful, thank you!

Just to make sure I understand, you're using auto-layout to size a label contained within a tableview header, and you don't want that to be any bigger than the tableview itself. Is that right?

If you don't mind helping provide some more information, I'd love to help debug this some more. Would you mind checking out a branch with some extra debugging information added?

https://github.com/justinseanmartin/KIF/tree/jmartin/debugging-table-view-cell

If so, would you mind running the smallest reproduction of the issue that you can and send me the console logs? You can find my email in my github bio.

**Comment by kenji21** [comment]
In fact the data is loaded via a network call. Header label is hidden during loading, and will contains "No data" or will have a "Last update date" and a fixed height of 128pt after data parsed and stored into core data. Labels (in header an in cells) are using custom fonts, but this doesn't helped to reproduce the issue in a separate project (copied view controller xib file to this new project), registered Nib cells to the tableView (as in real project), but issue never appeared in the "smaller" project...
Just mailed the log to you

**Comment by RtgrV** [comment]
Works awesome with our project.

**Comment by mikelupo** [comment]
@justinseanmartin Finally! This will merge. There were several changes to the files I submitted since last November and I had to really merge this carefully. I removed the .travis.yml commits from this stream and squashed three of my own commits on this branch to make the merge go smoother.
Let's please take aim to get this in. Our users are begging us.

To the rest of the users on this thread, since this commit is in sync with master (as of this writing) do you want to try it out first and give us some feedback before we merge to master?

**Comment by justinseanmartin** [comment]
Yep, put a comment in the issue #1007, but I'll reiterate here my apology for dragging my feet on this for so long. Let me take a look quick.

Also, Travis is failing a bunch of tests, so we should get those green before merging.

File: Additions/UIView-KIFAdditions.m [hunk 6]
```diff
@@ -236,8 +253,17 @@ - (UIAccessibilityElement *)accessibilityElementMatchingBlock:(BOOL(^)(UIAccessi
...
+                    firstIndexPath = indexPath;
+                } else {
+                    if ([firstIndexPath compare:indexPath] == NSOrderedDescending) {
+                        firstIndexPath = indexPath;
+                    }
+                }
             }];
-            
+
+			BOOL animationEnabled = [KIFUITestActor testActorAnimationsEnabled];
```
Comment (justinseanmartin) [inline Additions/UIView-KIFAdditions.m]: NIT (since you need to push again): Spaces are used consistently throughout the file, please match.

File: Additions/UIView-KIFAdditions.m [hunk 7]
```diff
@@ -236,8 +253,17 @@ - (UIAccessibilityElement *)accessibilityElementMatchingBlock:(BOOL(^)(UIAccessi
                 if (indexPath) {
                     [indexPathsForVisibleRows addObject:indexPath];
                 }
+                if (firstIndexPath == nil) {
```
Comment (justinseanmartin) [inline Additions/UIView-KIFAdditions.m]: NIT: This is effectively the same as the single condition:

```
    if (!firstIndexPath || ([firstIndexPath compare:indexPath] == NSOrderedDescending)) {
        firstIndexPath = indexPath;
    }
```

File: Additions/UIView-KIFAdditions.m [hunk 8]
```diff
@@ -225,9 +225,26 @@ - (UIAccessibilityElement *)accessibilityElementMatchingBlock:(BOOL(^)(UIAccessi
...
+
+        CGPoint scrollContentOffset = {-1.0, -1.0};
+        UIScrollView *scrollView = nil;
         if ([self isKindOfClass:[UITableView class]]) {
+            //special case for UIPickerView (which has a private class UIPickerTableView)
+
+            for (UIView *view in [self subviews])
+            {
+                NSString * subViewName = [NSString stringWithFormat:@"%@", [view class]];
+                if ([subViewName containsString:@"UIPicker"] )
```
Comment (justinseanmartin) [inline Additions/UIView-KIFAdditions.m]: Should we consider doing this for all table views and not just ones for picker views? (e.g. leave the views scrolled to their original position if they aren't a match). I saw some cases where the UI was scrolled to a position that is different than before.

This isn't necessary, but it would be nice to have consistency with the previous behavior and that of a user who isn't interacting with the UI leaving it unmodified.

File: Additions/UIView-KIFAdditions.m [hunk 9]
```diff
@@ -249,33 +275,34 @@ - (UIAccessibilityElement *)accessibilityElementMatchingBlock:(BOOL(^)(UIAccessi
...
                     CFRunLoopRunInMode(UIApplicationCurrentRunMode, delay, false);
-                    
-                    // Now try finding the element again
                     return [self accessibilityElementMatchingBlock:matchBlock];
                 }
             }
+            if (firstIndexPath) {
+                [tableView scrollToRowAtIndexPath:firstIndexPath atScrollPosition:UITableViewScrollPositionTop animated:NO];
+            }
+			//if we're in a picker (scrollView), let's make sure we set the position back to how it was last set.
```
Comment (justinseanmartin) [inline Additions/UIView-KIFAdditions.m]: NIT: tabs here again too

**Comment by justinseanmartin** [comment]
Completed the review. Mostly tiny style things, and the one question about scroll position in general.

**Comment by justinseanmartin** [comment]
One other thing to call: This does exercise app code differently than before. This change identified an area of the app where we were improperly using cell reuse identifiers in our table views. 

I just wanted to call out that this change might break tests for some people. At least in our app though, it is only doing so in ways where app code is broken and needs fixing.

**Comment by justinseanmartin** [comment]
There is another bug that I've known about for a while, but hadn't gotten around to fixing that this change started causing in our app. If a table view cell contains a matching element, and that element is full offscreen but the tableViewCell is partially onscreen, we won't scroll it into view and tapping the element will fail. The changed scrolling behavior in this PR causes that preexisting issue to be tripped in our tests. I took this as an opportunity to fix that issue however. I'll put up a separate PR with that fix.

File: Additions/UIView-KIFAdditions.m (hunk 9 above)
Comment (mikelupo) [reply Additions/UIView-KIFAdditions.m]: Yeah, for some reason, our team uses tabs in all of our projects. Make my community software life hell.

File: Additions/UIView-KIFAdditions.m (hunk 8 above)
Comment (mikelupo) [reply Additions/UIView-KIFAdditions.m]: I decided to leave this alone. There was a reason we chose to do it this way, and I can't recall the exact thought behind it. We have some mileage on this since last Nov and I don't want to introduce something that breaks the fix.

**Comment by justinseanmartin** [comment]
Travis tests are broken and need to be fixed before this can merge. Thanks for following up on my comments.

**Comment by mikelupo** [comment]
Specific to this commit or is it a more general thing?




-----Original Message-----

**Comment by justinseanmartin** [comment]
It looks like it is specific to this commit. The health status is reported at the top of the README.md for master and is green. It can also be seen here: https://travis-ci.org/kif-framework/KIF/branches

**Comment by justinseanmartin** [comment]
I've rekicked the CI builds again to see if they fail in the same way, but it looked like some tests that were broken from the changes made in this PR.

**Comment by mikelupo** [comment]
Grrr, custom picker tests need some love now. I won’t be able to tend to this till later tonight eastern time.

**Comment by justinseanmartin** [comment]
Interesting, now the picker tests work on all platforms/devices except Xcode 7. Thoughts on what it could be?

**Comment by mikelupo** [comment]
Initial investigation points towards it being the iPad2. I am using Xcode 9.2 - iPad2 sim with iOS 8.4. 
100% Reproducible there. 
Not sure what is actually happening though. I probably missed some edge case. I did try to look into it and nothing (even stepping through the code) is jumping out at me. 


It's unfortunate that my fix last night didn't finish this task. I am traveling today and cannot give this the priority it deserves for probably the next few weeks.
I realize that this is a priority for our users. 
Please avail yourself. I am not offended if you (or anyone else) completely rewrites my code.


Mike


-----Original Message-----

**Comment by qzim** [comment]
Any update?

**Comment by mikelupo** [comment]
@qzim Yes. I need some help to debug an issue on the iPad 2 picker tests. Ya game? Pull this and run the picker tests that failed in Travis. Unless @justinseanmartin says to move forward as-is I cannot commit this

**Comment by qzim** [comment]
Why not drop support for 8.x ?

**Comment by mikelupo** [comment]
Might make sense as iOS 11 is out but I can’t make that decision alone.

**Comment by avalanched** [comment]
I agree with @qzim, https://data.apteligent.com/ios/ indicates a 0.46% iOS 8 usage
